
#port number
server:
  port: 9092
# database specific properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

#key clock related properties
keycloak:
  realm: myrealm
  auth-server-url: http://localhost:7688
  resource: myclient
  public-client: true
  bearer-only: true



